apiVersion: apps/v1

kind: Deployment

metadata:
  name: orders-depl

spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders

  template:
    metadata:
      labels:
        app: orders

    spec:
      containers:
        - name: orders
          image: hmdrzadev/orders
          env:
            - name: JWT_KEY #this is the name of env as show up INSIDE OF CONTAINER as process.env
              valueFrom:
                secretKeyRef:
                  name: jwt-secret #this is the name of the object we created as secret
                  key: JWT_KEY
            - name: MONGO_URI
              value: mongodb://orders-mongo-srv:27017/orders
            - name: NATS_URL
              value: http://nats-srv:4222
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service

metadata:
  name: orders-srv

spec:
  selector:
    app: orders
  ports:
    - name: orders
      protocol: TCP
      port: 3000
      targetPort: 3000
