apiVersion: apps/v1

kind: Deployment

metadata:
  name: payments-depl

spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments

  template:
    metadata:
      labels:
        app: payments

    spec:
      containers:
        - name: payments
          image: hmdrzadev/payments
          env:
            - name: JWT_KEY #this is the name of env as show up INSIDE OF CONTAINER as process.env
              valueFrom:
                secretKeyRef:
                  name: jwt-secret #this is the name of the object we created as secret
                  key: JWT_KEY

            - name: STRIPE_KEY #this is the name of env as show up INSIDE OF CONTAINER as process.env
              valueFrom:
                secretKeyRef:
                  name: stripe-secret #this is the name of the object we created as secret
                  key: STRIPE_KEY

            - name: MONGO_URI
              value: mongodb://payments-mongo-srv:27017/payments
            - name: NATS_URL
              value: http://nats-srv:4222
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service

metadata:
  name: payments-srv

spec:
  selector:
    app: payments
  ports:
    - name: payments
      protocol: TCP
      port: 3000
      targetPort: 3000
